### ISSUE TITLE
Won't run on ruby 2.2.0 rails 4.1.4

### ISSUE THREAD

**Issue by deemytch** [NathanielWroblewski/schemapper#1]
When it was installed into `$home`, running inside project root gives me:

``` ruby
# schemapper --help
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
/home/username/.gem/ruby/2.2.0/gems/schemapper-0.0.2/bin/schemapper:17:in ``': No such file or directory - open (Errno::ENOENT)
    from /home/username/.gem/ruby/2.2.0/gems/schemapper-0.0.2/bin/schemapper:17:in `<top (required)>'
    from /home/username/.gem/ruby/2.2.0/bin/schemapper:23:in `load'
    from /home/username/.gem/ruby/2.2.0/bin/schemapper:23:in `<main>'
code 1
```

If I add schemapper into Gemfile, then `bundle install`, I get:

``` ruby
# schemapper 
/home/username/project/vendor/ruby/2.2.0/gems/schemapper-0.0.2/lib/schemapper.rb:3:in `<top (required)>': undefined method `eager_load!' for nil:NilClass (NoMethodError)
    from /home/username/.gem/ruby/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `require'
    from /home/username/.gem/ruby/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /home/username/.gem/ruby/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `each'
    from /home/username/.gem/ruby/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `block in require'
    from /home/username/.gem/ruby/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `each'
    from /home/username/.gem/ruby/2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `require'
    from /home/username/.gem/ruby/2.2.0/gems/bundler-1.7.11/lib/bundler.rb:134:in `require'
    from /home/username/project/config/application.rb:8:in `<top (required)>'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/username/project/config/environment.rb:2:in `<top (required)>'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/username/.gem/ruby/2.2.0/gems/schemapper-0.0.2/bin/../lib/schemapper.rb:1:in `<main>'
/home/username/.gem/ruby/2.2.0/gems/schemapper-0.0.2/bin/schemapper:17:in ``': No such file or directory - open (Errno::ENOENT)
    from /home/username/.gem/ruby/2.2.0/gems/schemapper-0.0.2/bin/schemapper:17:in `<top (required)>'
    from /home/username/.gem/ruby/2.2.0/bin/schemapper:23:in `load'
    from /home/username/.gem/ruby/2.2.0/bin/schemapper:23:in `<main>'
code 1
```

WDIW?

**Comment by NathanielWroblewski** [comment]
Hmm, I haven't revisited this in a long time, so it's possible there are breaking changes in the new rails.  I'll take a peek over the weekend and get back to you.

**Comment by NathanielWroblewski** [comment]
This error: 

```
/home/username/project/vendor/ruby/2.2.0/gems/schemapper-0.0.2/lib/schemapper.rb:3:in `<top (required)>': undefined method `eager_load!' for nil:NilClass (NoMethodError)
```

shows that it is likely not properly loading the `config/environment.rb` file, as `Rails.application.eager_load!` fails because `Rails.application` is nil.

This could either be caused by running the `schemapper` command from a directory other than the project root, or by a misplaced Rails `config/environment.rb` file.

I'll update the readme to show you the flow through the code, which is super short, and that will hopefully help you debug this issue.

**Comment by NathanielWroblewski** [comment]
I've added [some documentation](https://github.com/NathanielWroblewski/schemapper/blob/master/README.md#explanation-of-code) to help you debug further.  Let me know if you have any other questions.
